"""Initial migration

Revision ID: 019bdcc7ee55
Revises: 
Create Date: 2026-08-31 16:18:30.526116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '019bdcc7ee55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('designations',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('designation_id', sa.UUID(), nullable=False),
    sa.Column('experience_years', sa.DECIMAL(precision=2, scale=2), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('job_postings',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('designation_id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', name='employment_type'), nullable=False),
    sa.Column('experience_years', sa.DECIMAL(precision=2, scale=2), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('salary', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_reminder_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', 'COMPLETED', name='job_posting_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('designation_id', sa.UUID(), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', name='employment_type'), nullable=True),
    sa.Column('experience_years', sa.DECIMAL(precision=2, scale=2), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('salary', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('applications',
    sa.Column('job_posting_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'INTERVIEWED', 'REJECTED', 'SELECTED', 'WITHDRAWN', name='application_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('APPLICATION_SHORTLISTED', 'APPLICATION_REJECTED', 'APPLICATION_SELECTED', 'JOB_POSTING_CLOSED', 'DEADLINE_REMINDER', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('job_posting_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('applications')
    op.drop_table('job_templates')
    op.drop_table('job_postings')
    op.drop_table('employees')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_table('designations')
    op.drop_table('departments')
    # ### end Alembic commands ###
