"""Fix decimal precision for experience_years

Revision ID: 45b007426523
Revises: eb2102968b1e
Create Date: 2026-09-01 12:18:12.630391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b007426523'
down_revision: Union[str, Sequence[str], None] = 'eb2102968b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_templates', 'experience_years',
               existing_type=sa.NUMERIC(precision=2, scale=2),
               type_=sa.DECIMAL(precision=4, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_templates', 'experience_years',
               existing_type=sa.DECIMAL(precision=4, scale=2),
               type_=sa.NUMERIC(precision=2, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
