"""2-create index

Revision ID: 689425c9904c
Revises: 019bdcc7ee55
Create Date: 2026-08-31 18:10:43.271375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689425c9904c'
down_revision: Union[str, Sequence[str], None] = '019bdcc7ee55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_employee_id'), 'applications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_applications_job_posting_id'), 'applications', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_designation_id'), 'employees', ['designation_id'], unique=False)
    op.create_index(op.f('ix_employees_full_name'), 'employees', ['full_name'], unique=False)
    op.create_unique_constraint(None, 'employees', ['id'])
    op.create_index(op.f('ix_job_postings_department_id'), 'job_postings', ['department_id'], unique=False)
    op.create_index(op.f('ix_job_postings_designation_id'), 'job_postings', ['designation_id'], unique=False)
    op.create_index(op.f('ix_job_postings_title'), 'job_postings', ['title'], unique=False)
    op.create_index(op.f('ix_job_templates_designation_id'), 'job_templates', ['designation_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_job_templates_designation_id'), table_name='job_templates')
    op.drop_index(op.f('ix_job_postings_title'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_designation_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_department_id'), table_name='job_postings')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_index(op.f('ix_employees_full_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_designation_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_posting_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_employee_id'), table_name='applications')
    # ### end Alembic commands ###
