NAME_MAX_LENGTH = 255
SHORT_TEXT_MAX_LENGTH = 100
LONG_TEXT_MAX_LENGTH = 1000  # Optional, if you ever use long VARCHARs

EMAIL_MAX_LENGTH = 255
EMPLOYEE_CODE_MAX_LENGTH = 50

TOKEN_HASH_MAX_LENGTH = 255